"use client";

import { useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";

export type DirectionsValue = { parking_latitude: string; parking_longitude: string; parking_description: string; general_directions: string; public_transport: string; walking_path: string; entrance_description: string };
type TextKey = keyof DirectionsValue;
function parseCoordinate(value: string) { const normalized = value.trim().replace(",", "."); return normalized ? Number(normalized) : null; }

export default function DirectionsForm({ courseId, initialValue }: { courseId: string; initialValue: DirectionsValue }) {
    const [value, setValue] = useState(initialValue); const [saving, setSaving] = useState(false); const [locating, setLocating] = useState(false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false);
    function update(key: TextKey, next: string) { setValue((current) => ({ ...current, [key]: next })); setSaved(false); }
    function usePosition() {
        if (!navigator.geolocation || locating) return setError("Location is not available in this browser.");
        setLocating(true); setError(null);
        navigator.geolocation.getCurrentPosition((position) => { setValue((current) => ({ ...current, parking_latitude: String(position.coords.latitude), parking_longitude: String(position.coords.longitude) })); setLocating(false); setSaved(false); }, () => { setError("Your location could not be read. You can enter the coordinates manually."); setLocating(false); }, { enableHighAccuracy: true, timeout: 15000 });
    }
    async function save() {
        if (saving) return; setError(null); setSaved(false);
        const latitude = parseCoordinate(value.parking_latitude); const longitude = parseCoordinate(value.parking_longitude);
        if ((latitude === null) !== (longitude === null)) return setError("Enter both parking coordinates, or leave both empty.");
        if (latitude !== null && (!Number.isFinite(latitude) || latitude < -90 || latitude > 90)) return setError("Parking latitude must be between -90 and 90.");
        if (longitude !== null && (!Number.isFinite(longitude) || longitude < -180 || longitude > 180)) return setError("Parking longitude must be between -180 and 180.");
        setSaving(true);
        const { error: saveError } = await supabaseBrowser.rpc("upsert_course_directions_v1", { p_course_id: courseId, p_parking_latitude: latitude, p_parking_longitude: longitude, p_parking_description: value.parking_description, p_general_directions: value.general_directions, p_public_transport: value.public_transport, p_walking_path: value.walking_path, p_entrance_description: value.entrance_description });
        if (saveError) setError("Directions could not be saved. Your changes are still here."); else setSaved(true);
        setSaving(false);
    }
    const areaClass = "mt-2 w-full resize-y rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none transition placeholder:text-gray-600 focus:border-blue-400/60 focus:ring-2 focus:ring-blue-400/15";
    return <div className="mt-6 space-y-6"><section className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-2xl shadow-black/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Parking location</h2><p className="mt-1 text-sm text-gray-400">Latitude and longitude are stored as one coherent pair.</p></div><button type="button" onClick={usePosition} disabled={locating} className="rounded-xl border border-blue-400/30 bg-blue-500/10 px-4 py-2 text-sm font-semibold text-blue-200 transition hover:bg-blue-500/20 disabled:opacity-50">{locating ? "Finding position…" : "Use my position"}</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Parking latitude" value={value.parking_latitude} onChange={(next) => update("parking_latitude", next)} placeholder="59.12345" /><Field label="Parking longitude" value={value.parking_longitude} onChange={(next) => update("parking_longitude", next)} placeholder="10.12345" /></div><label className="mt-4 block text-sm font-semibold text-gray-300">Parking information<textarea rows={3} value={value.parking_description} onChange={(event) => update("parking_description", event.target.value)} placeholder="Where to park, fees and capacity…" className={areaClass} /></label></section>
        <section className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-2xl shadow-black/20"><h2 className="text-lg font-semibold">How to get there</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><TextArea label="General directions" value={value.general_directions} onChange={(next) => update("general_directions", next)} placeholder="How to reach the course by car" /><TextArea label="Public transport" value={value.public_transport} onChange={(next) => update("public_transport", next)} placeholder="Nearest bus stop or train station" /><TextArea label="Walking path" value={value.walking_path} onChange={(next) => update("walking_path", next)} placeholder="Path from parking to hole 1" /><TextArea label="Entrance information" value={value.entrance_description} onChange={(next) => update("entrance_description", next)} placeholder="Entrance location and useful signs" /></div></section>
        <section className="sticky bottom-4 rounded-2xl border border-white/10 bg-[#10131a]/95 p-4 shadow-2xl shadow-black/40 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}{saved && <p role="status" className="text-sm text-emerald-300">Directions saved.</p>}{!error && !saved && <p className="text-sm text-gray-500">Save to update the course directions.</p>}</div><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-blue-500 px-5 py-2.5 text-sm font-semibold transition hover:bg-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-300/50 disabled:opacity-60">{saving ? "Saving…" : "Save directions"}</button></div></section></div>;
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label><span className="text-sm font-semibold text-gray-300">{label}</span><input inputMode="decimal" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none transition placeholder:text-gray-600 focus:border-blue-400/60 focus:ring-2 focus:ring-blue-400/15" /></label>; }
function TextArea({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label><span className="text-sm font-semibold text-gray-300">{label}</span><textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full resize-y rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none transition placeholder:text-gray-600 focus:border-blue-400/60 focus:ring-2 focus:ring-blue-400/15" /></label>; }
